version: "2.1"

services:
      
  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.11.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

  flink:
    image: ecg/flink_1.4.0-prometheus-hadoop28-scala_2.11
    container_name: flink
    ports:
      - "6121:6121"
      - "6122:6122"
      - "6123:6123"
      - "8081:8081"
      - "9249:9249"
    links:
      - kafka:kafka
    command: local
    volumes:
      - "./flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml"
      - "./target:/app"

